In [3]:
pip install tensorflow

In [8]:
import tensorflow as tf
import numpy as np
print("tensor version: ", tf.__version__)

tensor version:  2.19.0


In [9]:
scalar=tf.constant(7)
print(scalar)

tf.Tensor(7, shape=(), dtype=int32)


In [10]:
vector=tf.constant([1,2,3])
print(vector)

tf.Tensor([1 2 3], shape=(3,), dtype=int32)


In [12]:
matrix=tf.constant([[1,2,3],[4,5,6]])
print(matrix)

tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)


In [21]:
a = tf.constant(20)
b = tf.constant(5)
print("Addition:", tf.add(a, b))
print("Subtraction:", tf.subtract(a, b))
print("Multiplication:", tf.multiply(a, b))
print("Division:", tf.divide(a, b))

Addition: tf.Tensor(25, shape=(), dtype=int32)
Subtraction: tf.Tensor(15, shape=(), dtype=int32)
Multiplication: tf.Tensor(100, shape=(), dtype=int32)
Division: tf.Tensor(4.0, shape=(), dtype=float64)


In [20]:
a = tf.constant([20, 40, 60])
b = tf.constant([1, 2, 3])

print("Addition:", tf.add(a, b))
print("Subtraction:", tf.subtract(a, b))
print("Multiplication:", tf.multiply(a, b))
print("Division:", tf.divide(a, b))

Addition: tf.Tensor([21 42 63], shape=(3,), dtype=int32)
Subtraction: tf.Tensor([19 38 57], shape=(3,), dtype=int32)
Multiplication: tf.Tensor([ 20  80 180], shape=(3,), dtype=int32)
Division: tf.Tensor([20. 20. 20.], shape=(3,), dtype=float64)


In [22]:
a = tf.constant([[1, 2], [3, 4]])
b = tf.constant([[5, 6], [7, 8]])

print("Addition:", tf.add(a, b))
print("Subtraction:", tf.subtract(a, b))
print("Multiplication:", tf.multiply(a, b))
print("Division:", tf.divide(a, b))

Addition: tf.Tensor(
[[ 6  8]
 [10 12]], shape=(2, 2), dtype=int32)
Subtraction: tf.Tensor(
[[-4 -4]
 [-4 -4]], shape=(2, 2), dtype=int32)
Multiplication: tf.Tensor(
[[ 5 12]
 [21 32]], shape=(2, 2), dtype=int32)
Division: tf.Tensor(
[[0.2        0.33333333]
 [0.42857143 0.5       ]], shape=(2, 2), dtype=float64)


In [23]:
tensor = tf.constant([[1, 2, 3], [4, 5, 6]])

print("Data Type:", tensor.dtype)
print("Shape:", tensor.shape)
print("Number of Dimensions:", tf.rank(tensor)) # rank of matrix
print("Number of Dimensions:", tensor.ndim) # dimensions of matrix

Data Type: <dtype: 'int32'>
Shape: (2, 3)
Number of Dimensions: tf.Tensor(2, shape=(), dtype=int32)
Number of Dimensions: 2


In [24]:
numpy_array = np.array([[1, 2, 3], [4, 5, 6]])

tensor = tf.convert_to_tensor(numpy_array)

print("NumPy Array:\n", numpy_array) #numpy array
print("TensorFlow Tensor:\n", tensor) #tensorflow tensor

NumPy Array:
 [[1 2 3]
 [4 5 6]]
TensorFlow Tensor:
 tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int64)
